version: '3.8'
services:
  backend:
    build: ./backend
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - database
      
  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_dev

volumes:
  postgres_data: