version: '3.8'
services:
  postgres:
    container_name: postgres
    restart: 'always'
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - xbot_db:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  xbot_db: